[etcd]
cca-etcd ansible_host=192.168.56.10

[controlplane]
cca-ctrl-1 ansible_host=192.168.56.11
# cca-ctrl-2 ansible_host=192.168.56.12

[workers]
cca-worker-1 ansible_host=192.168.56.20 node_id=worker-1
cca-worker-2 ansible_host=192.168.56.21 node_id=worker-2
# cca-worker-3 ansible_host=192.168.56.22 node_id=worker-3

[ccattler:children]
controlplane
workers

[all:vars]
ansible_user=vagrant
